# Generated by Django 4.0.2 on 2022-02-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportVersionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_version_name', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, upload_to='documents/')),
            ],
            options={
                'db_table': 'loginSystem_cart',
                'managed': True,
            },
        ),
    ]
