# Generated by Django 4.0.2 on 2022-02-13 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'loginSystem_Report',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReportVersionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_version_name', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='RedSeerFiles')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginSystem.reportmodel')),
            ],
            options={
                'db_table': 'loginSystem_ReportVersion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReportUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginSystem.reportmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loginSystem_ReportUser',
                'managed': True,
            },
        ),
    ]
