# Generated by Django 4.0.2 on 2022-02-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportversionmodel',
            name='file',
            field=models.FileField(blank=True, upload_to='message/%Y/%m/%d/'),
        ),
        migrations.AlterModelTable(
            name='reportversionmodel',
            table='loginSystem_ReportVersion',
        ),
    ]
