# Generated by Django 4.0.2 on 2022-02-09 11:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystem', '0002_alter_reportversionmodel_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'loginSystem_Report',
                'managed': True,
            },
        ),
    ]
