# Generated by Django 4.0.2 on 2022-02-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystem', '0002_alter_reportversionmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportversionmodel',
            name='link',
            field=models.TextField(default='http://127.0.0.1:8000/media/message/2022/02/25/Insurance_9OQCmFU.xlsx'),
        ),
    ]
