# Generated by Django 4.0.2 on 2022-02-09 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystem', '0003_reportmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportversionmodel',
            name='report',
            field=models.ForeignKey(default='0cee57e4-abb7-4ba0-9b52-9af7b1f43fd9', on_delete=django.db.models.deletion.CASCADE, to='loginSystem.reportmodel'),
            preserve_default=False,
        ),
    ]
